# Generated by Django 6.0 on 2025-12-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
    ]
