# Generated by Django 6.0 on 2025-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anbiyam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('village', models.CharField(max_length=60)),
                ('collection_agent', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'anbiyam',
            },
        ),
    ]
