# Generated by Django 6.0 on 2025-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_no', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('book_no', models.IntegerField()),
                ('anbiyam', models.IntegerField()),
                ('week', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Disbursed'), (3, 'Closed'), (4, 'Rejected')])),
                ('is_eligible', models.IntegerField()),
                ('approval_stats', models.TextField()),
                ('amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_status', models.IntegerField()),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
