# Generated by Django 6.0 on 2025-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('from_book', models.IntegerField()),
                ('to_book', models.IntegerField()),
                ('loan_date', models.DateTimeField()),
                ('loan_week', models.IntegerField()),
                ('adjustment_week', models.IntegerField()),
                ('adjustment_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('amount_type', models.IntegerField(choices=[(1, 'adjustment'), (2, 'cash')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adjustment',
            },
        ),
    ]
