# Generated by Django 6.0 on 2025-12-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adjustment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adjustment',
            table='adjustments',
        ),
    ]
