# Generated by Django 6.0 on 2025-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_no', models.IntegerField()),
                ('name', models.TextField()),
                ('anbiyam', models.IntegerField()),
                ('village', models.TextField()),
                ('guardian', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
