# Generated by Django 6.0 on 2025-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.IntegerField()),
                ('sunday_date', models.DateField()),
            ],
            options={
                'db_table': 'weeks',
            },
        ),
    ]
